### ISSUE TITLE
Example image that wasn't parsed correctly

### ISSUE THREAD

**Issue by dsjoerg** [Elucidation/ChessboardScreenshotHtml5#5]
Hello!  This is such an excellent project idea!

In case it's helpful, here's an image that wasn't parsed correctly:
![board](https://user-images.githubusercontent.com/783273/44550385-14704a80-a6f2-11e8-99be-bcb2e99aade7.png)

What it came up with: `R1PKQP1R/2P1PP1P/P1NP1N2/1P1p2K1/b3p3/2n2n2/ppp2ppp/1kr1q2r`

As you will see, it messed up the bishops on the 8th rank, and misidentified one of the black bishops as an extra white king

![image](https://user-images.githubusercontent.com/783273/44550406-2ce06500-a6f2-11e8-85bc-a3e08fde3be6.png)

**Comment by Elucidation** [comment]
Great link thanks! It's likely the model fails on these images because it doesn't have such a stripey background in it's dataset (it's only pulled from lichess/chess and similar type sites). 

If it's possible to get a 100 or so of these types of images with the correct fen associated with it, I can add it to the training dataset.
